dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3


before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - mvn test -B
  - cd wps_scripts && travis_retry ./gradlew test --info --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock


cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


